name: Deploy Backend (Railway) and Frontend (Vercel)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger Railway deploy - server
        if: ${{ secrets.RAILWAY_SERVER_HOOK_URL != '' }}
        run: |
          curl -fsSL -X POST "$RAILWAY_SERVER_HOOK_URL"
        env:
          RAILWAY_SERVER_HOOK_URL: ${{ secrets.RAILWAY_SERVER_HOOK_URL }}

      - name: Trigger Railway deploy - simulator
        if: ${{ secrets.RAILWAY_SIMULATOR_HOOK_URL != '' }}
        run: |
          curl -fsSL -X POST "$RAILWAY_SIMULATOR_HOOK_URL"
        env:
          RAILWAY_SIMULATOR_HOOK_URL: ${{ secrets.RAILWAY_SIMULATOR_HOOK_URL }}

      - name: Wait for Railway to roll out (grace period)
        run: |
          echo "Sleeping 90s to allow Railway to roll out..."
          sleep 90

      - name: Trigger Vercel rebuild
        if: ${{ secrets.VERCEL_BUILD_HOOK_URL != '' }}
        run: |
          curl -fsSL -X POST "$VERCEL_BUILD_HOOK_URL"
        env:
          VERCEL_BUILD_HOOK_URL: ${{ secrets.VERCEL_BUILD_HOOK_URL }}

      - name: Done
        run: echo "Deployment hooks triggered."



